variable "vpc_id" {}
variable "subnet_id" {}
variable "availability_zone" {}
variable "env_prefix" {}
variable "my_ip" {}
variable "instance_type" {}
variable "public_key_location" {}
variable "user_data_script_location" {}
variable "image-name" {}